### ISSUE TITLE
Hardware decoding not working after newest update

### ISSUE THREAD

**Issue by lilithwhite** [flathub/com.parsecgaming.parsec#11] opened 2021-02-20 14:22 UTC
After the latest update of Parsec it seems to be unable to use hardware decoding when streaming from my Windows 10 host. I rolled back to commit 9bec7799484d2cc98e408ba6e363223c9d4674e24e3914d18669306b658dc546 and it worked fine again. I'm on Pop!_OS 20.10.

Nothing unusual in the host logs but the client log shows this:
[D 2021-02-20 16:15:59] stun4         = 52.86.26.213:3478
[D 2021-02-20 16:16:00] net           = BUD|::ffff:192.168.0.193|21233
[I 2021-02-20 16:16:00] * vaapi_init/WelsCreateDecoder[275] = -1
[D 2021-02-20 16:16:00] decoder       = software

**Comment by SISheogorath** [comment] 2021-02-20 16:20
That might be aligned with #9. We decided to upgrade the runtime to 20.08 since 19.08 is already quite old. I'm, not sure why it broke, but I also can't reproduce it, right now, since I decided to cancel my Cloud gaming machine for this month.

However, if you like, you can might help investigate. For example by sharing what hardware you try to run on and if you have the flatpak vaapi plugin installed: `org.freedesktop.Platform.VAAPI.Intel` in the version 20.08.

**Comment by lilithwhite** [comment] 2021-02-21 03:28
I have org.freedesktop.Platform.VAAPI.Intel installed for both version 19.08 and 20.08:
flatpak list | grep VAAPI
Intel	org.freedesktop.Platform.VAAPI.Intel		19.08	flathub	system
Intel	org.freedesktop.Platform.VAAPI.Intel		20.08	flathub	system

My client is the Lenovo Legion Y520 laptop:
Intel Core i7-7700HQ
GeForce GTX 1050 Ti Mobile
16GB RAM

**Comment by lilithwhite** [comment] 2021-04-10 09:43
I found some more info for this as I had the exact same issue with the official deb package. Apparently Ubuntu 20.04 is missing the package vdpau-va-driver which is required for parsec. I installed it from the official Debian repo and it worked then. More info on the bug here: https://bugs.launchpad.net/ubuntu/+source/libva-utils/+bug/1890815

**Comment by boistordu** [comment] 2021-05-01 00:13
in fedora 34, it doesn't work either. I'm always on software decoder in place of my hardware decoder
gefore 1030 
no vaapi in flathub for my part, that I can see at least. 
I have installed right now the VAAPI for 20.08 from flathub as requested. 
for the nvidia part : 
```
nvidia-440-100	org.freedesktop.Platform.GL.nvidia-440-100		1.4	flathub	system
nvidia-440-44	org.freedesktop.Platform.GL.nvidia-440-44		1.4	flathub	system
nvidia-440-59	org.freedesktop.Platform.GL.nvidia-440-59		1.4	flathub	system
nvidia-440-64	org.freedesktop.Platform.GL.nvidia-440-64		1.4	flathub	system
nvidia-450-66	org.freedesktop.Platform.GL.nvidia-450-66		1.4	flathub	system
nvidia-455-28	org.freedesktop.Platform.GL.nvidia-455-28		1.4	flathub	system
nvidia-455-38	org.freedesktop.Platform.GL.nvidia-455-38		1.4	flathub	system
nvidia-455-45-01	org.freedesktop.Platform.GL.nvidia-455-45-01		1.4	flathub	system
nvidia-460-39	org.freedesktop.Platform.GL.nvidia-460-39		1.4	flathub	system
nvidia-460-56	org.freedesktop.Platform.GL.nvidia-460-56		1.4	flathub	system
nvidia-460-67	org.freedesktop.Platform.GL.nvidia-460-67		1.4	flathub	system
nvidia-465-24-02	org.freedesktop.Platform.GL.nvidia-465-24-02		1.4	flathub	system
```
and after all that it's still under software decoder

**Comment by SISheogorath** [comment] 2021-05-24 21:54
I'll close this issue in favour of #9

**Closed by SISheogorath** 2021-05-24 21:54 UTC
